# Generated by Django 3.1.4 on 2021-03-27 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20210327_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={},
        ),
    ]
